-- Generated by scripts/make-fixtures.ts; do not edit.
local A = ...
return {
  addon = {
    version = "0.1.0"
  },
  capturedAt = 1790799000,
  client = {
    build = "0.0.0",
    flavour = "forever",
    interface = 0
  },
  completedAt = 1790799012,
  money = 123456789,
  schema = "toadsbank.snapshot",
  schemaVersion = 1,
  snapshotId = "spineshatter-bankalt-1790799000-a1b2",
  source = {
    guild = "Toads",
    kind = "guildBank",
    realm = "Spineshatter",
    region = "EU"
  },
  stable = true,
  tabs = A{
    {
      capacity = 98,
      index = 1,
      name = "P\195\182tions",
      observedAt = 1790799004,
      slots = A{
        {
          count = 1,
          itemId = 22832,
          link = "|cffffffff|Hitem:22832::::::::70:::::|h[Super Mana Potion]|h|r",
          slot = 1
        },
        {
          count = 8,
          itemId = 22829,
          link = "|cffffffff|Hitem:22829::::::::70:::::|h[Super Healing Potion]|h|r",
          slot = 2
        },
        {
          count = 15,
          itemId = 22854,
          link = "|cffffffff|Hitem:22854::::::::70:::::|h[Flask of Relentless Assault]|h|r",
          slot = 3
        },
        {
          count = 2,
          itemId = 22861,
          link = "|cffffffff|Hitem:22861::::::::70:::::|h[Flask of Blinding Light]|h|r",
          slot = 4
        },
        {
          count = 9,
          itemId = 22866,
          link = "|cffffffff|Hitem:22866::::::::70:::::|h[Flask of Pure Death]|h|r",
          slot = 5
        },
        {
          count = 16,
          itemId = 22838,
          link = "|cffffffff|Hitem:22838::::::::70:::::|h[Haste Potion]|h|r",
          slot = 6
        },
        {
          count = 3,
          itemId = 13444,
          link = "|cffffffff|Hitem:13444::::::::70:::::|h[Major Mana Potion]|h|r",
          slot = 7
        },
        {
          count = 10,
          itemId = 28102,
          link = "|cffffffff|Hitem:28102::::::::70:::::|h[Onslaught Elixir]|h|r",
          slot = 8
        },
        {
          count = 17,
          itemId = 21886,
          link = "|cff1eff00|Hitem:21886::::::::70:::::|h[Primal Life]|h|r",
          slot = 9
        },
        {
          count = 4,
          itemId = 22457,
          link = "|cff1eff00|Hitem:22457::::::::70:::::|h[Primal Mana]|h|r",
          slot = 10
        },
        {
          count = 11,
          itemId = 22832,
          link = "|cffffffff|Hitem:22832::::::::70:::::|h[Super Mana Potion]|h|r",
          slot = 11
        },
        {
          count = 18,
          itemId = 22829,
          link = "|cffffffff|Hitem:22829::::::::70:::::|h[Super Healing Potion]|h|r",
          slot = 12
        },
        {
          count = 5,
          itemId = 22854,
          link = "|cffffffff|Hitem:22854::::::::70:::::|h[Flask of Relentless Assault]|h|r",
          slot = 13
        },
        {
          count = 12,
          itemId = 22861,
          link = "|cffffffff|Hitem:22861::::::::70:::::|h[Flask of Blinding Light]|h|r",
          slot = 14
        },
        {
          count = 19,
          itemId = 22866,
          link = "|cffffffff|Hitem:22866::::::::70:::::|h[Flask of Pure Death]|h|r",
          slot = 15
        },
        {
          count = 6,
          itemId = 22838,
          link = "|cffffffff|Hitem:22838::::::::70:::::|h[Haste Potion]|h|r",
          slot = 16
        },
        {
          count = 13,
          itemId = 13444,
          link = "|cffffffff|Hitem:13444::::::::70:::::|h[Major Mana Potion]|h|r",
          slot = 17
        },
        {
          count = 20,
          itemId = 28102,
          link = "|cffffffff|Hitem:28102::::::::70:::::|h[Onslaught Elixir]|h|r",
          slot = 18
        },
        {
          count = 7,
          itemId = 21886,
          link = "|cff1eff00|Hitem:21886::::::::70:::::|h[Primal Life]|h|r",
          slot = 19
        },
        {
          count = 14,
          itemId = 22457,
          link = "|cff1eff00|Hitem:22457::::::::70:::::|h[Primal Mana]|h|r",
          slot = 20
        },
        {
          count = 1,
          itemId = 22832,
          link = "|cffffffff|Hitem:22832::::::::70:::::|h[Super Mana Potion]|h|r",
          slot = 21
        },
        {
          count = 8,
          itemId = 22829,
          link = "|cffffffff|Hitem:22829::::::::70:::::|h[Super Healing Potion]|h|r",
          slot = 22
        },
        {
          count = 15,
          itemId = 22854,
          link = "|cffffffff|Hitem:22854::::::::70:::::|h[Flask of Relentless Assault]|h|r",
          slot = 23
        },
        {
          count = 2,
          itemId = 22861,
          link = "|cffffffff|Hitem:22861::::::::70:::::|h[Flask of Blinding Light]|h|r",
          slot = 24
        },
        {
          count = 9,
          itemId = 22866,
          link = "|cffffffff|Hitem:22866::::::::70:::::|h[Flask of Pure Death]|h|r",
          slot = 25
        },
        {
          count = 16,
          itemId = 22838,
          link = "|cffffffff|Hitem:22838::::::::70:::::|h[Haste Potion]|h|r",
          slot = 26
        },
        {
          count = 3,
          itemId = 13444,
          link = "|cffffffff|Hitem:13444::::::::70:::::|h[Major Mana Potion]|h|r",
          slot = 27
        },
        {
          count = 10,
          itemId = 28102,
          link = "|cffffffff|Hitem:28102::::::::70:::::|h[Onslaught Elixir]|h|r",
          slot = 28
        },
        {
          count = 17,
          itemId = 21886,
          link = "|cff1eff00|Hitem:21886::::::::70:::::|h[Primal Life]|h|r",
          slot = 29
        },
        {
          count = 4,
          itemId = 22457,
          link = "|cff1eff00|Hitem:22457::::::::70:::::|h[Primal Mana]|h|r",
          slot = 30
        },
        {
          count = 11,
          itemId = 22832,
          link = "|cffffffff|Hitem:22832::::::::70:::::|h[Super Mana Potion]|h|r",
          slot = 31
        },
        {
          count = 18,
          itemId = 22829,
          link = "|cffffffff|Hitem:22829::::::::70:::::|h[Super Healing Potion]|h|r",
          slot = 32
        },
        {
          count = 5,
          itemId = 22854,
          link = "|cffffffff|Hitem:22854::::::::70:::::|h[Flask of Relentless Assault]|h|r",
          slot = 33
        },
        {
          count = 12,
          itemId = 22861,
          link = "|cffffffff|Hitem:22861::::::::70:::::|h[Flask of Blinding Light]|h|r",
          slot = 34
        },
        {
          count = 19,
          itemId = 22866,
          link = "|cffffffff|Hitem:22866::::::::70:::::|h[Flask of Pure Death]|h|r",
          slot = 35
        },
        {
          count = 6,
          itemId = 22838,
          link = "|cffffffff|Hitem:22838::::::::70:::::|h[Haste Potion]|h|r",
          slot = 36
        },
        {
          count = 13,
          itemId = 13444,
          link = "|cffffffff|Hitem:13444::::::::70:::::|h[Major Mana Potion]|h|r",
          slot = 37
        },
        {
          count = 20,
          itemId = 28102,
          link = "|cffffffff|Hitem:28102::::::::70:::::|h[Onslaught Elixir]|h|r",
          slot = 38
        },
        {
          count = 7,
          itemId = 21886,
          link = "|cff1eff00|Hitem:21886::::::::70:::::|h[Primal Life]|h|r",
          slot = 39
        },
        {
          count = 14,
          itemId = 22457,
          link = "|cff1eff00|Hitem:22457::::::::70:::::|h[Primal Mana]|h|r",
          slot = 40
        }
      },
      status = "observed"
    },
    {
      capacity = 98,
      index = 2,
      name = "Mats \34raid\34",
      observedAt = 1790799008,
      slots = A{
        {
          count = 10,
          itemId = 21886,
          link = "|cff1eff00|Hitem:21886::::::::70:::::|h[Primal Life]|h|r",
          slot = 1
        },
        {
          count = 7,
          itemId = 22457,
          link = "|cff1eff00|Hitem:22457::::::::70:::::|h[Primal Mana]|h|r",
          slot = 5
        },
        {
          count = 3,
          itemId = 13444,
          slot = 98
        }
      },
      status = "observed"
    },
    {
      capacity = 98,
      index = 3,
      name = "Officers",
      observedAt = 1790799012,
      slots = A{},
      status = "unknown"
    }
  },
  uploader = {
    name = "Bankalt",
    realm = "Spineshatter"
  }
}
