/**
 * Writes contracts/fixtures from the reference TypeScript codec. Run `npm run fixtures` after a contract change and
 * commit the result; the addon's busted specs and the service's contract tests both read these files (TB-DM-03).
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  type Json,
  type Snapshot,
  canonicalJson,
  crc32Hex,
  encodeParts,
  formatPart,
  partHeader,
  utf8Encode,
} from '../packages/domain/src/index';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', 'contracts', 'fixtures');
export const FIXTURE_NOW = 1_790_800_000;

const ITEMS: Array<[number, string, string]> = [
  [22832, 'Super Mana Potion', 'ffffffff'],
  [22829, 'Super Healing Potion', 'ffffffff'],
  [22854, 'Flask of Relentless Assault', 'ffffffff'],
  [22861, 'Flask of Blinding Light', 'ffffffff'],
  [22866, 'Flask of Pure Death', 'ffffffff'],
  [22838, 'Haste Potion', 'ffffffff'],
  [13444, 'Major Mana Potion', 'ffffffff'],
  [28102, 'Onslaught Elixir', 'ffffffff'],
  [21886, 'Primal Life', 'ff1eff00'],
  [22457, 'Primal Mana', 'ff1eff00'],
];

function link(itemId: number, name: string, colour: string): string {
  return `|c${colour}|Hitem:${itemId}::::::::70:::::|h[${name}]|h|r`;
}

export function goldenSnapshot(): Snapshot {
  const potions = Array.from({ length: 40 }, (_, i) => {
    const [itemId, name, colour] = ITEMS[i % ITEMS.length] as [number, string, string];
    return { slot: i + 1, itemId, count: 1 + ((i * 7) % 20), link: link(itemId, name, colour) };
  });
  const mats = [
    { slot: 1, itemId: 21886, count: 10, link: link(21886, 'Primal Life', 'ff1eff00') },
    { slot: 5, itemId: 22457, count: 7, link: link(22457, 'Primal Mana', 'ff1eff00') },
    { slot: 98, itemId: 13444, count: 3 },
  ];
  return {
    schema: 'toadsbank.snapshot',
    schemaVersion: 1,
    snapshotId: 'spineshatter-bankalt-1790799000-a1b2',
    addon: { version: '0.1.0' },
    client: { flavour: 'forever', build: '0.0.0', interface: 0 },
    source: { kind: 'guildBank', guild: 'Toads', realm: 'Spineshatter', region: 'EU' },
    uploader: { name: 'Bankalt', realm: 'Spineshatter' },
    capturedAt: 1_790_799_000,
    completedAt: 1_790_799_012,
    stable: true,
    money: 123_456_789,
    tabs: [
      { index: 1, name: 'Pötions', status: 'observed', capacity: 98, observedAt: 1_790_799_004, slots: potions },
      { index: 2, name: 'Mats "raid"', status: 'observed', capacity: 98, observedAt: 1_790_799_008, slots: mats },
      { index: 3, name: 'Officers', status: 'unknown', capacity: 98, observedAt: 1_790_799_012, slots: [] },
    ],
  };
}

/** Lua table literal for the addon specs; arrays are wrapped in A{} so empty ones stay arrays. */
function toLua(value: Json, indent = ''): string {
  if (value === null) return 'nil';
  if (typeof value === 'boolean' || typeof value === 'number') return String(value);
  if (typeof value === 'string') {
    return `"${[...utf8Encode(value)].map((b) => (b === 34 || b === 92 || b < 32 || b > 126 ? `\\${b}` : String.fromCharCode(b))).join('')}"`;
  }
  const next = `${indent}  `;
  if (Array.isArray(value))
    return `A{${value.map((v) => `\n${next}${toLua(v, next)}`).join(',')}${value.length ? `\n${indent}` : ''}}`;
  const keys = Object.keys(value).sort();
  return `{${keys.map((k) => `\n${next}${k} = ${toLua(value[k] as Json, next)}`).join(',')}\n${indent}}`;
}

function write(path: string, content: string): void {
  mkdirSync(dirname(join(root, path)), { recursive: true });
  writeFileSync(join(root, path), content);
}

function main(): void {
  const snapshot = goldenSnapshot();
  const canonical = canonicalJson(snapshot as unknown as Json);
  const bytes = utf8Encode(canonical);
  const parts = encodeParts(bytes, snapshot.snapshotId);
  write('golden/snapshot.json', `${JSON.stringify(snapshot, null, 2)}\n`);
  write(
    'golden/snapshot.lua',
    `-- Generated by scripts/make-fixtures.ts; do not edit.\nlocal A = ...\nreturn ${toLua(snapshot as unknown as Json)}\n`,
  );
  write('golden/snapshot.canonical.json', canonical);
  write('golden/parts.txt', `${parts.map(formatPart).join('\n\n')}\n`);
  write('golden/crc32.txt', `${crc32Hex(bytes)}\n`);

  const cases: Array<{ file: string; stage: 'transport' | 'schema'; code: string }> = [];
  const invalid = (name: string, stage: 'transport' | 'schema', code: string, text: string) => {
    write(`invalid/${name}.txt`, text);
    cases.push({ file: `${name}.txt`, stage, code });
  };
  const reencode = (value: unknown) => {
    const b = utf8Encode(canonicalJson(value as Json));
    return encodeParts(b, snapshot.snapshotId).map(formatPart).join('\n\n');
  };

  const duplicateSlot = structuredClone(snapshot);
  (duplicateSlot.tabs[1] as Snapshot['tabs'][number]).slots.push({ slot: 5, itemId: 22457, count: 1 });
  invalid('duplicate-slot', 'schema', 'duplicate_slot', reencode(duplicateSlot));

  const future = structuredClone(snapshot);
  future.completedAt = FIXTURE_NOW + 86_400;
  invalid('future-timestamp', 'schema', 'future_timestamp', reencode(future));

  // 13 supplementary-plane characters: 13 code points but 26 UTF-16 code units, over the 24 an uploader name allows.
  const wideName = structuredClone(snapshot);
  wideName.uploader.name = '\u{1F438}'.repeat(13);
  invalid('utf16-length', 'schema', 'string_length', reencode(wideName));

  const badCrc = parts.map((p) => ({ ...p, crc32: p.crc32 === '00000000' ? '00000001' : '00000000' }));
  invalid('bad-crc', 'transport', 'crc_mismatch', badCrc.map(formatPart).join('\n\n'));

  const [p1, p2] = parts as [(typeof parts)[number], (typeof parts)[number]];
  const altered = { ...p2, payload: `${p2.payload.slice(0, -8)}AAAAAAAA` };
  invalid('conflicting-part', 'transport', 'conflicting_part', [...parts, altered].map(formatPart).join('\n\n'));

  invalid(
    'oversize-part-count',
    'transport',
    'too_many_parts',
    `${partHeader({ ...p1, index: 1, total: 801 })}\n${p1.payload}\n`,
  );

  write('invalid/cases.json', `${JSON.stringify({ now: FIXTURE_NOW, cases }, null, 2)}\n`);
}

main();
